export enum DEMOGRAPHIC {
  SHONEN = 'shonen',
  SHOJO = 'shojo',
  SEINEN = 'seinen',
  JOSEI = 'josei',
  KODOMO = 'kodomo',
}

export const DEMOGRAPHIC_LABELS: Record<DEMOGRAPHIC, string> = {
  [DEMOGRAPHIC.SHONEN]: 'Shōnen',
  [DEMOGRAPHIC.SHOJO]: 'Shōjo',
  [DEMOGRAPHIC.SEINEN]: 'Seinen',
  [DEMOGRAPHIC.JOSEI]: 'Josei',
  [DEMOGRAPHIC.KODOMO]: 'Kodomo',
};

export enum GENRE {
  ACTION = 'action',
  ADVENTURE = 'adventure',
  BL = 'bl',
  COMEDY = 'comedy',
  DANMEI = 'danmei',
  DRAMA = 'drama',
  FANTASY = 'fantasy',
  HORROR = 'horror',
  MYSTERY = 'mystery',
  PSYCHOLOGICAL = 'psychological',
  ROMANCE = 'romance',
  SCI_FI = 'sci_fi',
  SLICE_OF_LIFE = 'slice_of_life',
  SPORTS = 'sports',
  SUPERNATURAL = 'supernatural',
  THRILLER = 'thriller',
  ISEKAI = 'isekai',
  MECHA = 'mecha',
  HISTORICAL = 'historical',
  ECCHI = 'ecchi',
  HAREM = 'harem',
  YAOI = 'yaoi',
  YURI = 'yuri',
}

export const GENRE_LABELS: Record<GENRE, string> = {
  [GENRE.ACTION]: 'Acción',
  [GENRE.ADVENTURE]: 'Aventura',
  [GENRE.BL]: 'Boys Love',
  [GENRE.DANMEI]: 'Danmei',
  [GENRE.COMEDY]: 'Comedia',
  [GENRE.DRAMA]: 'Drama',
  [GENRE.FANTASY]: 'Fantasía',
  [GENRE.HORROR]: 'Terror',
  [GENRE.MYSTERY]: 'Misterio',
  [GENRE.PSYCHOLOGICAL]: 'Psicológico',
  [GENRE.ROMANCE]: 'Romance',
  [GENRE.SCI_FI]: 'Ciencia ficción',
  [GENRE.SLICE_OF_LIFE]: 'Recuentos de la vida',
  [GENRE.SPORTS]: 'Deportes',
  [GENRE.SUPERNATURAL]: 'Sobrenatural',
  [GENRE.THRILLER]: 'Suspense',
  [GENRE.ISEKAI]: 'Isekai',
  [GENRE.MECHA]: 'Mecha',
  [GENRE.HISTORICAL]: 'Histórico',
  [GENRE.ECCHI]: 'Ecchi',
  [GENRE.HAREM]: 'Harem',
  [GENRE.YAOI]: 'Yaoi',
  [GENRE.YURI]: 'Yuri',
};
